defaultPortal: wild7-dev
portals:
  - name: wild7
    portalId: 1687305
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLbhmdrRLxIOAA0AAAAA4A0AAAAAAEAYif5mINGN8AMo7ukMMhRXoCerIiJzz9Iqaelqjk8aNDbYAjovAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwD-_zE8AAAAAAAAYAAAAAAAAAhCFLfAW-FGad8wE8ewTZ6FavsLKUw-SgNuYTFSAFoA
        expiresAt: '2021-11-13T21:49:00.989Z'
    personalAccessKey: >-
      CiQyNGIyOTYzYi1hMjlhLTRkMzctYTM3Yy1jZDM4NzQ0MGEzYzMQif5mGNGN8AMqGQAF5pGCKKFKU4iYH0bFLxXSkb7Ifa3w_GlKA25hMQ
  - name: wild7-dev
    portalId: 20977602
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIDMwZDbLxIJAA0AAAAA4A0DGMKvgAog0Y3wAyju6QwyFOkVymJwb0eAjf4-4yEg0EQbTlENOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhRCxpamOwoxuIEjf3aIO6MDQ-d-Q0oDbmExUgBaAA
        expiresAt: '2021-12-13T04:32:38.919Z'
    personalAccessKey: >-
      CiRlODg4ZTYwMC03NDVlLTRmM2EtYTIzMC00NGY1YmRhYmFjM2EQwq-AChjRjfADKhkABeaRgk8D7rCvYu8lxKAy88Rx-38-02PoSgNuYTE
