defaultPortal: wild7-dev
portals:
  - name: wild7
    portalId: 1687305
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLbhmdrRLxIOAA0AAAAA4A0AAAAAAEAYif5mINGN8AMo7ukMMhRXoCerIiJzz9Iqaelqjk8aNDbYAjovAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwD-_zE8AAAAAAAAYAAAAAAAAAhCFLfAW-FGad8wE8ewTZ6FavsLKUw-SgNuYTFSAFoA
        expiresAt: '2021-11-13T21:49:00.989Z'
    personalAccessKey: >-
      CiQyNGIyOTYzYi1hMjlhLTRkMzctYTM3Yy1jZDM4NzQ0MGEzYzMQif5mGNGN8AMqGQAF5pGCKKFKU4iYH0bFLxXSkb7Ifa3w_GlKA25hMQ
  - name: wild7-dev
    portalId: 20977602
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI_J_4bmLxIJAA0AAAAA4A0DGMKvgAog0Y3wAyju6QwyFF-5aySkogn9LZsgeP1U-011RGczOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTWg47bit3mzIx5F6IvctIYPkhgN0oDbmExUgBaAA
        expiresAt: '2022-01-16T03:13:12.852Z'
    personalAccessKey: >-
      CiRlODg4ZTYwMC03NDVlLTRmM2EtYTIzMC00NGY1YmRhYmFjM2EQwq-AChjRjfADKhkABeaRgk8D7rCvYu8lxKAy88Rx-38-02PoSgNuYTE
