defaultPortal: wild7-dev
portals:
  - name: wild7
    portalId: 1687305
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLbhmdrRLxIOAA0AAAAA4A0AAAAAAEAYif5mINGN8AMo7ukMMhRXoCerIiJzz9Iqaelqjk8aNDbYAjovAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwD-_zE8AAAAAAAAYAAAAAAAAAhCFLfAW-FGad8wE8ewTZ6FavsLKUw-SgNuYTFSAFoA
        expiresAt: '2021-11-13T21:49:00.989Z'
    personalAccessKey: >-
      CiQyNGIyOTYzYi1hMjlhLTRkMzctYTM3Yy1jZDM4NzQ0MGEzYzMQif5mGNGN8AMqGQAF5pGCKKFKU4iYH0bFLxXSkb7Ifa3w_GlKA25hMQ
  - name: wild7-dev
    portalId: 20977602
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJ6q_P_vLxIJAA0AAAAA4A0DGMKvgAog0Y3wAyju6QwyFKt3zTh91iej1dc-VeifbhiMT5B4OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhRLyBmfUlBc8czFCWhDU2lk57jZNUoDbmExUgBaAA
        expiresAt: '2022-02-16T00:46:54.243Z'
    personalAccessKey: >-
      CiRlODg4ZTYwMC03NDVlLTRmM2EtYTIzMC00NGY1YmRhYmFjM2EQwq-AChjRjfADKhkABeaRgk8D7rCvYu8lxKAy88Rx-38-02PoSgNuYTE
